### ISSUE TITLE
Wasabi S3 Errors

### ISSUE THREAD

**Issue by r1chjames** [EnterpriseDB/barman#1064]
I've been using Wasabi S3-compatible storage using CNPG, however recently my backups have been failing with the following error:
`failure uploading data (An error occurred (InvalidRequest) when calling the UploadPart operation: Checksum Type mismatch occurred, expected checksum Type: null, actual checksum Type: crc32)`.

I can't pinpoint when it stopped working, however I'm running with the following config:
``` 
backup:
    barmanObjectStore:
      destinationPath: 's3://[REDACTED]-cnpg-backups/shared'
      endpointURL: 'https://s3.eu-west-1.wasabisys.com'
      s3Credentials:
        accessKeyId:
          name: wasabi-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: wasabi-secret
          key: ACCESS_SECRET_KEY
```
I'm unsure whether it's related to the change to `3.12`, just wondering if anyone else had seen something similar. I've moved to AWS S3 and it works so presumably it's a specific issue in the Wasabi implementation of S3 API.
