### ISSUE TITLE
boto3 >= 1.36 causes issues with some s3 providers

### ISSUE THREAD

**Issue by sdesbure** [EnterpriseDB/barman#1086]
Hello,

we're using barman through [https://cloudnative-pg.io/plugin-barman-cloud](plugin-barman-cloud). When upgrading from `0.4.1` to `0.5.0`, barman version bumped from `3.13.3` to `3.14.0`.

One changes is to remove pining on boto3 for version <= 1.46 ([BAR-637](https://github.com/EnterpriseDB/barman/commit/81fa7d7f3a62cebb43c2f3c049f0da1e38c6753a)).

Several S3 provider are actually not compatible with this version (see [Outscale](https://docs.outscale.com/en/userguide/AWS-SDK-and-CLI-Compatibility-Warning.html) for information but there are others) and then barman 1.34 cannot work with them :/

according to [AWS](https://docs.aws.amazon.com/sdkref/latest/guide/feature-dataintegrity.html), we can workaround it by setting two environment variables:

```shell
export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
```

I've tested it with plugin-barman-cloud (for information, this is how I did:

```yaml
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: my-os
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://backup/
    endpointURL: https://my-old-s3-service
    s3Credentials:
      accessKeyId:
        key: S3_ACCESS_KEY
        name: s3-backup-pg
      secretAccessKey:
        key: S3_SECRET_KEY
        name: s3-backup-pg
    wal:
      compression: snappy
  instanceSidecarConfiguration:
    env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
```
)

maybe it would be useful to add it in the documentation this workaround as all people using barman with "old" s3 services may be impacted

regards

[BAR-637]: https://enterprisedb.atlassian.net/browse/BAR-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
