### ISSUE TITLE
backup with truenas s3

### ISSUE THREAD

**Issue by zasim87** [EnterpriseDB/barman#862]
Hello everyone! I would appreciate any help.
We use Barman - Backup and Recovery Manager for [cnpg](https://github.com/cloudnative-pg)
Trying to run backups with truenas s3:
```
backup: 
    barmanObjectStore:
      destinationPath: "s3://bucket/"
      endpointURL: https://truenas.dom.mycompany.com:9000/
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
``` 
got the following error:
```
Could not connect to the endpoint URL: \"https://s3.dom.amazonaws.com/bucket\
``` 
probably it happens because truenas returns Region': 'dom'
I could manage it with
```
        region:
          name: s3-creds
          key: region
``` 
After the region is added, backups will work properly.

still looks like the URL combining is a bit strange:
```
\"https://s3.dom.amazonaws.com/bucket\
``` 
it takes region and puts it together with amazonaws.com

Is it expected behavior?
