### ISSUE TITLE
Backup to Linode ObjectStorage fails

### ISSUE THREAD

**Issue by alwinzwets** [EnterpriseDB/barman#957]
This might be related to issue #743. Also I'm not sure whether this is a Barman or a Linode issue. 
I'm trying to setup a backup strategy to Linode's Object Storage. I am using barman via cloudnative-pg 1.23.2. This fails with the following error:

```
{"level":"info","ts":"2024-07-04T09:09:09Z","msg":"Starting barman-cloud-backup","backupName":"backup-example","backupNamespace":"backup-example","logging_pod":"database-cluster-1","options":["--user","postgres","--name","backup-20240704090909","--gzip","--encryption","AES256","--jobs","2","--endpoint-url","https://nl-ams-1.linodeobjects.com","--cloud-provider","aws-s3","s3://bucketname/backups","database-cluster"]}
{"level":"info","ts":"2024-07-04T09:09:16Z","logger":"barman-cloud-backup","msg":"2024-07-04 09:09:16,434 [24983] ERROR: Backup failed uploading data (An error occurred (InvalidArgument) when calling the CreateMultipartUpload operation: Unknown)","pipe":"stderr","logging_pod":"database-cluster-1"}
{"level":"info","ts":"2024-07-04T09:09:16Z","logger":"barman-cloud-backup","msg":"2024-07-04 09:09:16,449 [24983] ERROR: Backup failed uploading backup.info file (An error occurred (InvalidArgument) when calling the PutObject operation: Unknown)","pipe":"stderr","logging_pod":"database-cluster-1"}
```

To reproduce, use the following configuration:

```yaml
backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: s3://bucketname/backups
      endpointURL: https://nl-ams-1.linodeobjects.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: database-cluster-backup-s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: database-cluster-backup-s3-creds
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 1
    retentionPolicy: 30d
    target: prefer-standby
```

The same configuration with an AWS or Wasabi Object Storage works as expected, for example with the following configuration:

```yaml
backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: s3://bucketname/backups
      endpointURL: https://s3.eu-central-1.wasabisys.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: database-cluster-backup-s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: database-cluster-backup-s3-creds
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 1
    retentionPolicy: 30d
    target: prefer-standby
```
    
The fact that the backup works with Wasabi and S3 made me reason the issue could be on Linode's side, so I filed a support ticket with them, referencing #743, with the following response: 

> ...
> Thank you for passing along those detail for us. It's important to note that our [Object Storage](https://www.linode.com/docs/products/storage/object-storage/get-started/) does support multipart uploads and is S3 compatible.
> 
> After reading through the thread you shared, it looks like this may be an issue with how the barman code interacts with our buckets. Since this is a third party source, our team won't be able to make any changes on that front. With that in mind, I would recommend bringing your findings to barmans support and/or submitting a bug request to see if they can help provide potential workarounds:
> 
> https://pgbarman.org/support/
> ...

Any ideas what could be the problem?

Thanks, 

Alwin

**Comment by gcalacoci** [comment]
Hi Alwin,

It seems that Linode object storage is not fully compatible with s3.

Barman uses boto3 lib (official aws python library) to execute multipart uploads into s3 buckets.
As a result, it is able to work, out of the box, with all the services that are fully S3-compatible, the fact that is working with wasabi (and obviously s3) as you reported, shows that.

Barman officially supports s3 only and is not possible for us to test Barman on all the "s3 compatible" services (that are a lot).

Said so, looking at the error you reported seems that something is possibly evaluated by Linode as not valid, so the first thing that comes to my mind is: is the URL to Linode a valid endpoint?

**Comment by alwinzwets** [comment]
Hi Giulio,

The endpoint is as per the [Linode docs](https://www.linode.com/docs/products/storage/object-storage/guides/urls/#cluster-url-s3-endpoint) and this setup does work in other applications (like Cyberduck for example) so I think the problem is not in the configuration. If I change the endpoint and/or the key/secret the backup fails as expected with an AccessDenied so at least there is some communication with the Linode platform.

Thanks for pointing out the use of boto3. I'll try to raise this info again with Linode. Hopefully they are willing to test the boto3 <>Linode integration on their end, this indeed sounds like the main suspect.

Thanks,
Alwin

**Comment by alwinzwets** [comment]
Response from Linode:

> Evening Alwin,
> 
> We do support Boto3 with our S3 compatible storage, and some of our oldest public communications are four years old. A thought came to mind that, perhaps, our implemented version of Boto3 may differ from Barman's compatibility requirement. So, I'll be checking with our developers to ask if they could confirm the version we're utilizing, but also suggest you doublecheck your version and our documents.
> 
> Here's a link to our Boto3 documentation which was updated in April, and another page with a search for Boto3.
> 
> [Using the AWS SDK for Python (boto3) with Object Storage | Linode Docs](https://www.linode.com/docs/products/storage/object-storage/guides/aws-sdk-for-python/)
> [Linode Questions matching boto3](https://www.linode.com/community/questions/search?query=boto3)
> I'll be leaving this support ticket open while we investigate this a bit further, but at this immediate moment I can say that Boto3 is implemented and we're compatible.
> 
> Best regards,

**Comment by alwinzwets** [comment]
It took a bit back and forth, but I have received a response from Linode on the error logs produced by the barman backup with a Linode ObjectStorage configuration.

> Hello Alwin,
> 
> Our Admins has reached back with an update. After reviewing the logs you've sent, they wanted to ask about your s3 configuration file and see if you wanted to use SSE-C and have it properly configured in your client.
>
> The configuration should look like this for using SSE-C:
>
> sse_customer_algorithm = AES256
> sse_customer_key = $KEY 
> You may also provide the configuration in the ticket if you have sanitized the critical information.
> 
> For any more questions or concerns, you may reach back in this ticket. We are here 24/7 for you.
>
> Sincerely,

Any ideas if there is such configuration in Barman and if so where I can find this, so I can provide this information to Linode?

**Comment by alwinzwets** [comment]
After weeks of back and forth with Linode support we came to the root cause of the compatibility issue between Barman and Linode's ObjectStorage.

The default storage method of AWS S3 is server side encryption with keys managed by AWS, SSE-S3. However, Linode does not support this feature and only supports server side encryption with client provided keys, SSE-C. When providing the ServerSideEncryption argument on the upload Linode assumes you want to use SSE-C and expects client provided encryption keys. If you do not provide these the upload will fail.

Linode confirmed to me that at the moment they do not support SSE-S3. Removing the encryption property for Barman solves the issue for me, although the data will be unencrypted.

This configuration does **not** work with Linode Object Storage
```yaml
backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: s3://bucketname/backups
      endpointURL: https://nl-ams-1.linodeobjects.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: database-cluster-backup-s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: database-cluster-backup-s3-creds
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 1
    retentionPolicy: 30d
    target: prefer-standby
```

This configuration **does** work with Linode Object Storage.
```yaml
backup:
    barmanObjectStore:
      data:
        compression: gzip
        jobs: 2
      destinationPath: s3://bucketname/backups
      endpointURL: https://nl-ams-1.linodeobjects.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: database-cluster-backup-s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: database-cluster-backup-s3-creds
      wal:
        compression: gzip
        maxParallel: 1
    retentionPolicy: 30d
    target: prefer-standby
```

When using cloudnative-pg the encryption key is set to AES256 by default. You need to manually overwrite this by providing `encryption=''` for both backup and wal.
